// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBMuc1hVo42dqmQCuuS3BZ1L2RONCkWKwk",
      authDomain: "flutter-flash-cards-6976c.firebaseapp.com",
      projectId: "flutter-flash-cards-6976c",
      storageBucket: "flutter-flash-cards-6976c.appspot.com",
      messagingSenderId: "182387056402",
      appId: "1:182387056402:web:3c99a0fd86aac6f1ffddcb"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuI5VgqYeuaSc6uxz8R7EKA36dUFnXvYE',
    appId: '1:182387056402:android:8a20a44bf5a80ed1ffddcb',
    messagingSenderId: '182387056402',
    projectId: 'flutter-flash-cards-6976c',
    storageBucket: 'flutter-flash-cards-6976c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtmxUIFWBclMlEgzAzwM_1HKwTgebIm2c',
    appId: '1:182387056402:ios:6ab3b179f050c3b8ffddcb',
    messagingSenderId: '182387056402',
    projectId: 'flutter-flash-cards-6976c',
    storageBucket: 'flutter-flash-cards-6976c.appspot.com',
    iosBundleId: 'com.example.flashCards',
  );
}